# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["solutions"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Setup Pages
        uses: actions/configure-pages@v6
      - name: Convert root README to index.html
        uses: davorg/readme-to-index@v1
        with:
          install_pandoc: true
      - name: Convert Part 1 README to index.html
        uses: davorg/readme-to-index@v1
        with:
          readme: exercises/part1-accessing-data/README.md
          output: exercises/part1-accessing-data/index.html
      - name: Convert Part 2 README to index.html
        uses: davorg/readme-to-index@v1
        with:
          readme: exercises/part2-manipulating-data/README.md
          output: exercises/part2-manipulating-data/index.html
      - name: Convert Part 3 README to index.html
        uses: davorg/readme-to-index@v1
        with:
          readme: exercises/part3-combining-data/README.md
          output: exercises/part3-combining-data/index.html
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          # Upload entire repository
          path: '.'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
